### ISSUE TITLE
The auto-import feature does not work any more.

### ISSUE THREAD

**Issue by mleise** [aBothe/D_Parser#189]
Used on any symbol, auto-import (Ctrl+Alt+Space) will always display an empty list as if the requested symbol could not be found in any module on the import path.
Already imported symbols are still resolved correctly and call-tips as well as semantic highlighting work on them. So they are generally visible to the parser.

**Comment by aBothe** [comment]
Sry that it takes longer than expected..couldn't find any time to get it done.
Well, I've recently rewrote some code pieces which caused this regression.

Now I'm doing proper tests and trying to do a nice and clean implementation.
I've also planned to auto-write Nested types:
```C#
class C { enum Nested {a,b,c} }

Nested // When hitting Ctrl+Alt+Space, there's gonna be C.Nested written.
```
