### ISSUE TITLE
IDE crash when template typed parameter's default value is set to the template name

### ISSUE THREAD

**Issue by CZDanol** [aBothe/D_Parser#192]
Hey,

in mono-d, this code crashes the ide (try adding a letter behind 'var = Template'):

```
module main;

private struct Template( void var = Template ) {}

void main() {
    Template!() instance;
}
```

this bug also crashes DMD:
https://issues.dlang.org/show_bug.cgi?id=14907

**Comment by aBothe** [comment]
Just ran the code, I seem to have fixed it meanwhile 🙈
